dist: trusty

addons:
  sonarcloud:
    organization: "testiamplus"
    token:
      secure: "t9GOS/WsykVP8OGdLawtlRJIKdpmTymQ0LLry+Xsg8tpp6VmmFrMWniS/j9mZEWM1LuIoipdU283/+n1dYscVgHG2f5gXg9EiBooBjpPFKtm3tc4DB5uCln6itETsNiCdMevIyShCEykXks2tjpRbj2p5dxWlth8g/EO8SIhCuxiwQ1ehUbTAFZbgNDu5LIUUorsrHzMQnTzV/dLqSC1Lx7BgnxvATAYCWGkpz6xVRP2TKuXTZV3k7r8gAxtb66R9M5DeBIvcbI+m5O/y5sPE+R1WrTqMUnddB+WP+d34xM69b4aC9VN/u+dsbOVAxG5y+USd+9PU+bs1Unam9AEw3ytWy3Vc7D/w3pCM88cJTjrJOsVJ2G8UAHFvmypNs63vgTc2IJu/S94Kl4E5S0mLo66c+TqRtFUpV6fH5FKgrsxWftHeMilOYcVtGPuIkD9nUedSI9Go0PC42KZx/nt8TZHrrrb1+LvSS3phY0fB8WHcfeYTVdLofwZ6V1a/aBwMJ+Jdlp4DkuakDR/ySp98FEbz4UNceZPUqcQWrZ1W3YDIS5O9eEiB2VS4AZyrLTOv8P++wxRTEgOzRosdZdrylxNE9GhgOssB2dRWf8WX022vGHhG8paGplSAVMsir9OtsPABL48P/wKsXnCXQovP71HS8Ri9WARxKgxL+pTqdU=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
