dist: trusty

addons:
  sonarcloud:
    organization: "testiamplus"
    token:
      secure: "0IZvjt8TE98Py6Ps9+mPdZKiGyzgmxJhBOoy0/MIHYso7CzcebzBypKjCis+mnd7GAd0rJBZXd6Dizp19pfYmS7c63JAsn1T1M7szmB3+IUUHlL7usLs1J/3OKQ1JA7TjpXCRfFPXWUZwZ3Uvt5CRWlh1a4FObd42DDYws7b5rP0zLhvOLfavJsDpzfLXGQj+CgMFjAYLr4WlICd5DYtqULC63kdrE8rcntYmeASo9OF5Dx/4usiSnb2jsw6T6XiVatqQjHfrJfe1dOLTWhXWYHPS5xIhtjXu7LGxO52zAZMwbOFjaBqU59cSA4lXPzzSjl97Liz/ZPb8DJap2ZRAsh1oMfqmihtjaXG/mzY9VNY/2ypAWPRUGTYw9do886pWV93Rnq3RGQRxjvm3MpqbQma4dANHt4YpKqxpktKearGsudlQQ8H3YujvYPIe0gafg/3SmvAcWfOmbwFcbTNz5XOO9ocUzK1Grg70dmxzIDIrxBEzpE1XzKHPBM6v4EXx9wnX7F1ghdIv7MV5rMqqhc4OxedsEkaTqMsrWbIUkEFTWwC3SLdY8C/81jbtVZw0iq8tuatZBAk9851dQ/aXK1VcAwJXQAScgQXgRjmH394rJaE0fdc7/7I8m/STuSoPdH40vM2cZS/howTTG1CXwLRpP+jiJo+eucSRQ4RdZo=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
