// Code generated by go-swagger; DO NOT EDIT.

package friends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/duladissa/friends_management/models"
)

// PostFriendsUpdatesSubscribeOKCode is the HTTP code returned for type PostFriendsUpdatesSubscribeOK
const PostFriendsUpdatesSubscribeOKCode int = 200

/*PostFriendsUpdatesSubscribeOK successful operation

swagger:response postFriendsUpdatesSubscribeOK
*/
type PostFriendsUpdatesSubscribeOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostFriendsUpdatesSubscribeOK creates PostFriendsUpdatesSubscribeOK with default headers values
func NewPostFriendsUpdatesSubscribeOK() *PostFriendsUpdatesSubscribeOK {

	return &PostFriendsUpdatesSubscribeOK{}
}

// WithPayload adds the payload to the post friends updates subscribe o k response
func (o *PostFriendsUpdatesSubscribeOK) WithPayload(payload *models.SuccessResponse) *PostFriendsUpdatesSubscribeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends updates subscribe o k response
func (o *PostFriendsUpdatesSubscribeOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsUpdatesSubscribeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsUpdatesSubscribeUnauthorizedCode is the HTTP code returned for type PostFriendsUpdatesSubscribeUnauthorized
const PostFriendsUpdatesSubscribeUnauthorizedCode int = 401

/*PostFriendsUpdatesSubscribeUnauthorized Unauthorized

swagger:response postFriendsUpdatesSubscribeUnauthorized
*/
type PostFriendsUpdatesSubscribeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsUpdatesSubscribeUnauthorized creates PostFriendsUpdatesSubscribeUnauthorized with default headers values
func NewPostFriendsUpdatesSubscribeUnauthorized() *PostFriendsUpdatesSubscribeUnauthorized {

	return &PostFriendsUpdatesSubscribeUnauthorized{}
}

// WithPayload adds the payload to the post friends updates subscribe unauthorized response
func (o *PostFriendsUpdatesSubscribeUnauthorized) WithPayload(payload *models.ErrorResponse) *PostFriendsUpdatesSubscribeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends updates subscribe unauthorized response
func (o *PostFriendsUpdatesSubscribeUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsUpdatesSubscribeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsUpdatesSubscribeNotFoundCode is the HTTP code returned for type PostFriendsUpdatesSubscribeNotFound
const PostFriendsUpdatesSubscribeNotFoundCode int = 404

/*PostFriendsUpdatesSubscribeNotFound Not Found.

swagger:response postFriendsUpdatesSubscribeNotFound
*/
type PostFriendsUpdatesSubscribeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsUpdatesSubscribeNotFound creates PostFriendsUpdatesSubscribeNotFound with default headers values
func NewPostFriendsUpdatesSubscribeNotFound() *PostFriendsUpdatesSubscribeNotFound {

	return &PostFriendsUpdatesSubscribeNotFound{}
}

// WithPayload adds the payload to the post friends updates subscribe not found response
func (o *PostFriendsUpdatesSubscribeNotFound) WithPayload(payload *models.ErrorResponse) *PostFriendsUpdatesSubscribeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends updates subscribe not found response
func (o *PostFriendsUpdatesSubscribeNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsUpdatesSubscribeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
