// Code generated by go-swagger; DO NOT EDIT.

package friends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/duladissa/friends_management/models"
)

// PostFriendsConnectionsOKCode is the HTTP code returned for type PostFriendsConnectionsOK
const PostFriendsConnectionsOKCode int = 200

/*PostFriendsConnectionsOK successful operation

swagger:response postFriendsConnectionsOK
*/
type PostFriendsConnectionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostFriendsConnectionsOK creates PostFriendsConnectionsOK with default headers values
func NewPostFriendsConnectionsOK() *PostFriendsConnectionsOK {

	return &PostFriendsConnectionsOK{}
}

// WithPayload adds the payload to the post friends connections o k response
func (o *PostFriendsConnectionsOK) WithPayload(payload *models.SuccessResponse) *PostFriendsConnectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends connections o k response
func (o *PostFriendsConnectionsOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsConnectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsConnectionsBadRequestCode is the HTTP code returned for type PostFriendsConnectionsBadRequest
const PostFriendsConnectionsBadRequestCode int = 400

/*PostFriendsConnectionsBadRequest Bad request

swagger:response postFriendsConnectionsBadRequest
*/
type PostFriendsConnectionsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsConnectionsBadRequest creates PostFriendsConnectionsBadRequest with default headers values
func NewPostFriendsConnectionsBadRequest() *PostFriendsConnectionsBadRequest {

	return &PostFriendsConnectionsBadRequest{}
}

// WithPayload adds the payload to the post friends connections bad request response
func (o *PostFriendsConnectionsBadRequest) WithPayload(payload *models.ErrorResponse) *PostFriendsConnectionsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends connections bad request response
func (o *PostFriendsConnectionsBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsConnectionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsConnectionsUnauthorizedCode is the HTTP code returned for type PostFriendsConnectionsUnauthorized
const PostFriendsConnectionsUnauthorizedCode int = 401

/*PostFriendsConnectionsUnauthorized Unauthorized

swagger:response postFriendsConnectionsUnauthorized
*/
type PostFriendsConnectionsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsConnectionsUnauthorized creates PostFriendsConnectionsUnauthorized with default headers values
func NewPostFriendsConnectionsUnauthorized() *PostFriendsConnectionsUnauthorized {

	return &PostFriendsConnectionsUnauthorized{}
}

// WithPayload adds the payload to the post friends connections unauthorized response
func (o *PostFriendsConnectionsUnauthorized) WithPayload(payload *models.ErrorResponse) *PostFriendsConnectionsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends connections unauthorized response
func (o *PostFriendsConnectionsUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsConnectionsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsConnectionsNotFoundCode is the HTTP code returned for type PostFriendsConnectionsNotFound
const PostFriendsConnectionsNotFoundCode int = 404

/*PostFriendsConnectionsNotFound Not Found.

swagger:response postFriendsConnectionsNotFound
*/
type PostFriendsConnectionsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsConnectionsNotFound creates PostFriendsConnectionsNotFound with default headers values
func NewPostFriendsConnectionsNotFound() *PostFriendsConnectionsNotFound {

	return &PostFriendsConnectionsNotFound{}
}

// WithPayload adds the payload to the post friends connections not found response
func (o *PostFriendsConnectionsNotFound) WithPayload(payload *models.ErrorResponse) *PostFriendsConnectionsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends connections not found response
func (o *PostFriendsConnectionsNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsConnectionsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
