// Code generated by go-swagger; DO NOT EDIT.

package friends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/duladissa/friends_management/models"
)

// PostFriendsUpdatesBlockOKCode is the HTTP code returned for type PostFriendsUpdatesBlockOK
const PostFriendsUpdatesBlockOKCode int = 200

/*PostFriendsUpdatesBlockOK successful operation

swagger:response postFriendsUpdatesBlockOK
*/
type PostFriendsUpdatesBlockOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostFriendsUpdatesBlockOK creates PostFriendsUpdatesBlockOK with default headers values
func NewPostFriendsUpdatesBlockOK() *PostFriendsUpdatesBlockOK {

	return &PostFriendsUpdatesBlockOK{}
}

// WithPayload adds the payload to the post friends updates block o k response
func (o *PostFriendsUpdatesBlockOK) WithPayload(payload *models.SuccessResponse) *PostFriendsUpdatesBlockOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends updates block o k response
func (o *PostFriendsUpdatesBlockOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsUpdatesBlockOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsUpdatesBlockUnauthorizedCode is the HTTP code returned for type PostFriendsUpdatesBlockUnauthorized
const PostFriendsUpdatesBlockUnauthorizedCode int = 401

/*PostFriendsUpdatesBlockUnauthorized Unauthorized

swagger:response postFriendsUpdatesBlockUnauthorized
*/
type PostFriendsUpdatesBlockUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsUpdatesBlockUnauthorized creates PostFriendsUpdatesBlockUnauthorized with default headers values
func NewPostFriendsUpdatesBlockUnauthorized() *PostFriendsUpdatesBlockUnauthorized {

	return &PostFriendsUpdatesBlockUnauthorized{}
}

// WithPayload adds the payload to the post friends updates block unauthorized response
func (o *PostFriendsUpdatesBlockUnauthorized) WithPayload(payload *models.ErrorResponse) *PostFriendsUpdatesBlockUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends updates block unauthorized response
func (o *PostFriendsUpdatesBlockUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsUpdatesBlockUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsUpdatesBlockNotFoundCode is the HTTP code returned for type PostFriendsUpdatesBlockNotFound
const PostFriendsUpdatesBlockNotFoundCode int = 404

/*PostFriendsUpdatesBlockNotFound Not Found.

swagger:response postFriendsUpdatesBlockNotFound
*/
type PostFriendsUpdatesBlockNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsUpdatesBlockNotFound creates PostFriendsUpdatesBlockNotFound with default headers values
func NewPostFriendsUpdatesBlockNotFound() *PostFriendsUpdatesBlockNotFound {

	return &PostFriendsUpdatesBlockNotFound{}
}

// WithPayload adds the payload to the post friends updates block not found response
func (o *PostFriendsUpdatesBlockNotFound) WithPayload(payload *models.ErrorResponse) *PostFriendsUpdatesBlockNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends updates block not found response
func (o *PostFriendsUpdatesBlockNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsUpdatesBlockNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
