// Code generated by go-swagger; DO NOT EDIT.

package friends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/duladissa/friends_management/models"
)

// PostFriendsConnectionsListOKCode is the HTTP code returned for type PostFriendsConnectionsListOK
const PostFriendsConnectionsListOKCode int = 200

/*PostFriendsConnectionsListOK successful operation

swagger:response postFriendsConnectionsListOK
*/
type PostFriendsConnectionsListOK struct {

	/*
	  In: Body
	*/
	Payload *models.FriendsListResponse `json:"body,omitempty"`
}

// NewPostFriendsConnectionsListOK creates PostFriendsConnectionsListOK with default headers values
func NewPostFriendsConnectionsListOK() *PostFriendsConnectionsListOK {

	return &PostFriendsConnectionsListOK{}
}

// WithPayload adds the payload to the post friends connections list o k response
func (o *PostFriendsConnectionsListOK) WithPayload(payload *models.FriendsListResponse) *PostFriendsConnectionsListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends connections list o k response
func (o *PostFriendsConnectionsListOK) SetPayload(payload *models.FriendsListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsConnectionsListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsConnectionsListUnauthorizedCode is the HTTP code returned for type PostFriendsConnectionsListUnauthorized
const PostFriendsConnectionsListUnauthorizedCode int = 401

/*PostFriendsConnectionsListUnauthorized Unauthorized

swagger:response postFriendsConnectionsListUnauthorized
*/
type PostFriendsConnectionsListUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsConnectionsListUnauthorized creates PostFriendsConnectionsListUnauthorized with default headers values
func NewPostFriendsConnectionsListUnauthorized() *PostFriendsConnectionsListUnauthorized {

	return &PostFriendsConnectionsListUnauthorized{}
}

// WithPayload adds the payload to the post friends connections list unauthorized response
func (o *PostFriendsConnectionsListUnauthorized) WithPayload(payload *models.ErrorResponse) *PostFriendsConnectionsListUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends connections list unauthorized response
func (o *PostFriendsConnectionsListUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsConnectionsListUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFriendsConnectionsListNotFoundCode is the HTTP code returned for type PostFriendsConnectionsListNotFound
const PostFriendsConnectionsListNotFoundCode int = 404

/*PostFriendsConnectionsListNotFound Not Found.

swagger:response postFriendsConnectionsListNotFound
*/
type PostFriendsConnectionsListNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostFriendsConnectionsListNotFound creates PostFriendsConnectionsListNotFound with default headers values
func NewPostFriendsConnectionsListNotFound() *PostFriendsConnectionsListNotFound {

	return &PostFriendsConnectionsListNotFound{}
}

// WithPayload adds the payload to the post friends connections list not found response
func (o *PostFriendsConnectionsListNotFound) WithPayload(payload *models.ErrorResponse) *PostFriendsConnectionsListNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post friends connections list not found response
func (o *PostFriendsConnectionsListNotFound) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFriendsConnectionsListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
