// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/duladissa/friends_management/restapi/operations/friends"
)

// NewFriendsManagementAPI creates a new FriendsManagement instance
func NewFriendsManagementAPI(spec *loads.Document) *FriendsManagementAPI {
	return &FriendsManagementAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		FriendsPostFriendsCommonListHandler: friends.PostFriendsCommonListHandlerFunc(func(params friends.PostFriendsCommonListParams) middleware.Responder {
			return middleware.NotImplemented("operation FriendsPostFriendsCommonList has not yet been implemented")
		}),
		FriendsPostFriendsConnectionsHandler: friends.PostFriendsConnectionsHandlerFunc(func(params friends.PostFriendsConnectionsParams) middleware.Responder {
			return middleware.NotImplemented("operation FriendsPostFriendsConnections has not yet been implemented")
		}),
		FriendsPostFriendsConnectionsListHandler: friends.PostFriendsConnectionsListHandlerFunc(func(params friends.PostFriendsConnectionsListParams) middleware.Responder {
			return middleware.NotImplemented("operation FriendsPostFriendsConnectionsList has not yet been implemented")
		}),
		FriendsPostFriendsUpdatesBlockHandler: friends.PostFriendsUpdatesBlockHandlerFunc(func(params friends.PostFriendsUpdatesBlockParams) middleware.Responder {
			return middleware.NotImplemented("operation FriendsPostFriendsUpdatesBlock has not yet been implemented")
		}),
		FriendsPostFriendsUpdatesListHandler: friends.PostFriendsUpdatesListHandlerFunc(func(params friends.PostFriendsUpdatesListParams) middleware.Responder {
			return middleware.NotImplemented("operation FriendsPostFriendsUpdatesList has not yet been implemented")
		}),
		FriendsPostFriendsUpdatesSubscribeHandler: friends.PostFriendsUpdatesSubscribeHandlerFunc(func(params friends.PostFriendsUpdatesSubscribeParams) middleware.Responder {
			return middleware.NotImplemented("operation FriendsPostFriendsUpdatesSubscribe has not yet been implemented")
		}),
	}
}

/*FriendsManagementAPI API definitions */
type FriendsManagementAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// FriendsPostFriendsCommonListHandler sets the operation handler for the post friends common list operation
	FriendsPostFriendsCommonListHandler friends.PostFriendsCommonListHandler
	// FriendsPostFriendsConnectionsHandler sets the operation handler for the post friends connections operation
	FriendsPostFriendsConnectionsHandler friends.PostFriendsConnectionsHandler
	// FriendsPostFriendsConnectionsListHandler sets the operation handler for the post friends connections list operation
	FriendsPostFriendsConnectionsListHandler friends.PostFriendsConnectionsListHandler
	// FriendsPostFriendsUpdatesBlockHandler sets the operation handler for the post friends updates block operation
	FriendsPostFriendsUpdatesBlockHandler friends.PostFriendsUpdatesBlockHandler
	// FriendsPostFriendsUpdatesListHandler sets the operation handler for the post friends updates list operation
	FriendsPostFriendsUpdatesListHandler friends.PostFriendsUpdatesListHandler
	// FriendsPostFriendsUpdatesSubscribeHandler sets the operation handler for the post friends updates subscribe operation
	FriendsPostFriendsUpdatesSubscribeHandler friends.PostFriendsUpdatesSubscribeHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *FriendsManagementAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *FriendsManagementAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *FriendsManagementAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *FriendsManagementAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *FriendsManagementAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *FriendsManagementAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *FriendsManagementAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the FriendsManagementAPI
func (o *FriendsManagementAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.FriendsPostFriendsCommonListHandler == nil {
		unregistered = append(unregistered, "friends.PostFriendsCommonListHandler")
	}

	if o.FriendsPostFriendsConnectionsHandler == nil {
		unregistered = append(unregistered, "friends.PostFriendsConnectionsHandler")
	}

	if o.FriendsPostFriendsConnectionsListHandler == nil {
		unregistered = append(unregistered, "friends.PostFriendsConnectionsListHandler")
	}

	if o.FriendsPostFriendsUpdatesBlockHandler == nil {
		unregistered = append(unregistered, "friends.PostFriendsUpdatesBlockHandler")
	}

	if o.FriendsPostFriendsUpdatesListHandler == nil {
		unregistered = append(unregistered, "friends.PostFriendsUpdatesListHandler")
	}

	if o.FriendsPostFriendsUpdatesSubscribeHandler == nil {
		unregistered = append(unregistered, "friends.PostFriendsUpdatesSubscribeHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *FriendsManagementAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *FriendsManagementAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *FriendsManagementAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *FriendsManagementAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *FriendsManagementAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *FriendsManagementAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the friends management API
func (o *FriendsManagementAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *FriendsManagementAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/friends/common/list"] = friends.NewPostFriendsCommonList(o.context, o.FriendsPostFriendsCommonListHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/friends/connections"] = friends.NewPostFriendsConnections(o.context, o.FriendsPostFriendsConnectionsHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/friends/connections/list"] = friends.NewPostFriendsConnectionsList(o.context, o.FriendsPostFriendsConnectionsListHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/friends/updates/block"] = friends.NewPostFriendsUpdatesBlock(o.context, o.FriendsPostFriendsUpdatesBlockHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/friends/updates/list"] = friends.NewPostFriendsUpdatesList(o.context, o.FriendsPostFriendsUpdatesListHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/friends/updates/subscribe"] = friends.NewPostFriendsUpdatesSubscribe(o.context, o.FriendsPostFriendsUpdatesSubscribeHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *FriendsManagementAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *FriendsManagementAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *FriendsManagementAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *FriendsManagementAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
