// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Friends Management
API definitions


    Schemes:
      http
      https
    Host: localhost
    BasePath: /api/v1
    Version: 0.0.1
    License: Copyright 2019 SPGroup. All rights reserved.

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
