// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FriendsListResponse List of friends along with the success.
// swagger:model FriendsListResponse
type FriendsListResponse struct {

	// success.
	Count int64 `json:"count,omitempty"`

	// List of friends.
	// Required: true
	Friends []string `json:"friends"`

	// success.
	// Required: true
	Success *bool `json:"success"`
}

// Validate validates this friends list response
func (m *FriendsListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFriends(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccess(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FriendsListResponse) validateFriends(formats strfmt.Registry) error {

	if err := validate.Required("friends", "body", m.Friends); err != nil {
		return err
	}

	return nil
}

func (m *FriendsListResponse) validateSuccess(formats strfmt.Registry) error {

	if err := validate.Required("success", "body", m.Success); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FriendsListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FriendsListResponse) UnmarshalBinary(b []byte) error {
	var res FriendsListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
