// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ReceiveUpdatesFriends receive updates friends
// swagger:model ReceiveUpdatesFriends
type ReceiveUpdatesFriends struct {

	// Sender.
	Sender string `json:"sender,omitempty"`

	// Text
	Text string `json:"text,omitempty"`
}

// Validate validates this receive updates friends
func (m *ReceiveUpdatesFriends) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReceiveUpdatesFriends) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReceiveUpdatesFriends) UnmarshalBinary(b []byte) error {
	var res ReceiveUpdatesFriends
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
