// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SubscribeFriends subscribe friends
// swagger:model SubscribeFriends
type SubscribeFriends struct {

	// Requestor for the subscription.
	Requestor string `json:"requestor,omitempty"`

	// Target of the subscription.
	Target string `json:"target,omitempty"`
}

// Validate validates this subscribe friends
func (m *SubscribeFriends) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubscribeFriends) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscribeFriends) UnmarshalBinary(b []byte) error {
	var res SubscribeFriends
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
